### ISSUE TITLE
custom File Associations with bash.zed

### ISSUE THREAD

**Issue by HenriqueNas** [d1y/bash.zed#6]
I want to associate some files as .bash:

I tried [this doc](https://zed.dev/docs/configuring-languages#file-associations) to set any file called _"pre-push"_ to be parsed as bash, but it didn't work... I think I might be using the wrong "file_type" key !!

I tried this with "bash", "bash.zed", "Bash", "BASH" and ".bash"... none worked:
```json
 "file_types": {
    "bash": ["pre-push"]
  }
```

I set the same file with other config like "Dart" and "C++", and it change the highlight of words for the file "pre-push".

**Comment by rizitis** [comment]
my scripts called *.SlackBuild I use this and works:
```
"file_types": {
    "bash": ["SlackBuild", "*.sh"],
    "SlackBuild": ["SlackBuild"]
  },
  ```

**Comment by HenriqueNas** [comment]
The key "bash" still not working 😞 ...

I also tried with other file names and extensions !
and putting others keys as config works fine

**Comment by HenriqueNas** [comment]
I solved by setting the file `pre-push` with the `Shell Script` _file_type key_:

```json
  "file_types": {
    "Shell Script": ["pre-push", "*.sh"],
    "env": [".env*"],
    "Dockerfile": ["Dockerfile*"]
  }
```
